config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  get 'profile', to: 'users#profile'
  resources :users
  resources :projects

  root to: 'projects#index'

  # API version 1
  # By adding namespace, Rails will automatically map that namespace to a directory matching the name under the controllers folder
  namespace :api,
    :path => "", #removes 'api' from the URL path
    :defaults => {:format => :json}, #sets json as default format in our routes
    :constraints => {:subdomain => "api"} do #creates the subdomain (api.myapp...)
      namespace :v1 do
        resources :projects
      end
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable

  has_attached_file :thumbnail, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects

  #paperclip
  has_attached_file :avatar,
    :styles => { :medium => "300x300>", :thumb => "30x30#" },
    :default_url => "/images/:style/missing.png",
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/api/v1/projects_controller.rb
class API::V1::ProjectsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :username, :description, :instructions, :link, :email, :password, :current_password) }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order('created_at DESC')

    @projects
  end

  def show
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to @project, notice: "El proyecto se ha creado correctamente"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path, notice: "Project deleted"
  end

  private
  def project_params
    params.require(:project).permit(:thumbnail, :title, :description, :tag_list, :instructions)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    # @user = current_user
  end

  # show user's page for logged in user
  def profile
    @user = current_user
    render 'users/profile'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :avatar, :usename, :description, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlabs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div id="top_bar">
      <div class="row">
        <div class="col-sm-12">
          <div class="col-sm-8">
            <nav class="navbar-default" style="background-color:transparent">
              <%= button_to 'HOME', root_path, :action => 'get', :method => 'get', class: 'btn btn-default link-mainbar btn-sm tpnt_button pull-left'%>
              <% if user_signed_in? %>
                <%= link_to('Create new project', new_project_path) %>
              <% end %>
            </nav>
          </div>

          <% if user_signed_in? %>
          <div class="col-sm-4">
            <%= button_to 'Sign out', destroy_user_session_path, :action => 'destroy', :method => 'delete', class: 'btn btn-sm text-capitalize btn-primary btn-mainbar pull-right'%>
            <%= link_to current_user.username , user_path(current_user.id), :action => 'get', :method => 'get', class: 'pull-right' %>
            <%= image_tag(current_user.avatar.url(:thumb)) %>
          </div>
        </div>
      </div>
          <% else %>
          <div class="col-sm-4">
            <%= button_to 'Sign Up', new_user_registration_path, :action => 'get', :method => 'get', class: 'btn btn-sm text-capitalize btn-primary btn-mainbar pull-right'%>
            <%= button_to 'Login', new_user_session_path, :action => 'get', :method => 'get', class: 'btn btn-default btn-sm text-capitalize btn-primary btn-mainbar pull-right'%>
          </div>
        </div>
      </div>
          <% end %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert" %>
  <% end %>

  <div class="row hero text-center">
    <h1 class="tagline">A space to Play and Make</h1>
    <p class="lead">Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
    <a class="btn btn-default link-mainbar" href="#" role="button">See projects</a>
  </div>

  <div class="container">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<!--
Inside your views, use the 'simple_form_for' with one of the Bootstrap form
classes, '.form-horizontal' or '.form-inline', as the following:

  = simple_form_for(@user, html: { class: 'form-horizontal' }) do |form|
-->

<%= simple_form_for @project, html: {multipart: true} do |f| %>
  <% if @project.errors.any? %>
    <p>
      <%= @project.errors.count %> prevented this recipe from saving.
    </p>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li>msg</li>
      <% end %>
    </ul>
  <% end %>

  <%= f.file_field :thumbnail %><br>
  <%= f.input :title, label: 'Título', input_html: {class: 'form-control'} %>
  <%= f.input :description, label: 'Descripción breve', input_html: {class: 'form-control'} %>
  <%= f.input :tag_list, label: 'Category', :collection => ['Science', 'Technology', 'Engineering', 'Art', 'Mathematics'], input_html: {class: 'btn btn-default dropdown-toggle', type: "button", id: "dropdownTags"} %>
  <!-- include = below to show the tags field -->
  <% f.input :tag_list, label: 'Tags (separated by commas)', input_html: {class: 'form-control'} %>

  <%= f.cktext_area :instructions, :ckeditor => {:uiColor => '#c1f5f5', :toolbar => 'mini'} %>


  <%= f.button :submit, label: 'Create', class: 'btn btn-default' %>
<% end %>

app/views/projects/edit.html.erb
<h1><%= @project.title %></h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects index</h1>

<% @projects.each do |p| %>
  <ul>
    <li class="project-card">
      <h4><%= link_to(p.title, project_path(p.id)) %></h4>
      <% if p.user %>
        <p>Author: <%= image_tag p.user.avatar.url(:thumb) %> <%= link_to p.user.username, user_path(p.user.id), :action => 'get', :method => 'get' %></p>
        <p>Category: <%= p.tag_list %></p>
      <% end %>
      <p><%== p.description %></p>
    </li>
  </ul>
<% end %>


<!--

<li class="card course syllabus topic-ios personalized" data-location="library" data-featurette="library-card" data-activity="syllabus/2002" id="Syllabus-2002">

  <a class="card-title" href="/library/objectoriented-objectivec">
    <div class="card-progress">
      <svg class="course-icon"></svg>
      <span class="estimate">4 hours</span>
    </div>

    <strong>Course</strong>
    <h3>Object-Oriented Objective-C</h3>
    <p class="description">
      Following directly from the Objective-C  Basics course, we'll explore critical concepts like classes, objects, methods, memory management, pointers and more. An essential course for iOS Development with Objective-C.
    </p>
  </a>

  <ul class="card-tags tags">
    <li class="topic-ios topic topic"><a data-filter-list-val="topic:ios" href="/library/topic:ios"><span>iOS</span></a></li><li class="difficulty"><span>Beginner</span></li>
    <li class="truncated-tags"><span></span><ul></ul></li>
  </ul>

  <ul class="card-actions">
    <li class="card-action resume">
      <a class="button primary" href="/library/objectoriented-objectivec/getting-oriented-objectoriented-that-is/introduction-to-objects-part-1">Start</a>
    </li>
    <li class="card-action secondary bookmarkable" data-featurette="bookmarkable" id="featurette-25">
      <a class="card-action-button bookmark" data-method="POST" rel="nofollow" href="/library/objectoriented-objectivec/pin">
        <svg preserveAspectRatio="xMinYMin meet" viewBox="0 0 16 16" class="star-small-icon"></svg>
      </a>
      <a class="card-action-button unbookmark" href="/library/objectoriented-objectivec/unpin">
        <svg preserveAspectRatio="xMinYMin meet" viewBox="0 0 18 18" class="loading-icon"></svg>
      </a>
    </li>
  </ul>
</li><!-- end project card -->

app/views/projects/new.html.erb
<h1>New project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<p><%== @project.thumbnail %></p>
<h1><%= @project.title %></h1>
<p>Author: <%= link_to(@project.user.username, @project.user) %></p>
<p>Category: <%= @project.tag_list %></p>
<p><%== @project.instructions %></p>


<% if user_signed_in? %>
  <% if current_user.email == @project.user.email %>
    <%= link_to 'Edit', edit_project_path %>
    <%= link_to 'Delete', project_path, method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
<% end %>

app/views/users/profile.html.erb
<h1><%= @user.email %></h1>

<% if user_signed_in? %>
  <%= link_to 'Edit Profile', edit_user_registration_path, :action => 'get', :method => 'get', class: 'pull-right'%>
<% end %>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

app/views/users/show.html.erb
<%= image_tag @user.avatar.url(:medium) %>

<h1><%= @user.username %></h1>
<% if user_signed_in? %>
  <% if current_user.email == @user.email %>
    <p><%= link_to 'Edit Profile', edit_user_registration_path, :action => 'get', :method => 'get'%></p>
    <!-- private data -->
    <p>Only showed in user's own profile page when user_signed_in</p>
  <% end %>
<% end %>

<!-- public data -->
<p>
  <strong>Link:</strong><a href="<%= @user.link %>"> <%= @user.link %></a><br>
  <strong>Email:</strong> <%= @user.email %>
</p>
<p>
  <%= @user.description %>
</p>